# Generated by Django 2.2.12 on 2021-02-24 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210224_0355'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='title',
            field=models.CharField(default=None, max_length=64),
        ),
    ]
