# Generated by Django 2.2.12 on 2021-02-26 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_comment_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.ManyToManyField(related_name='category', to='auctions.Category'),
        ),
    ]
